/**
 * The app's feedback vocabulary: every sound and buzz it can make, in one table.
 *
 * A cue pairs a sound with the haptic that belongs to it, because the two are
 * one event to the player — the card snaps and the phone answers. Volumes are
 * balanced here rather than in the files so the mix can be tuned by reading a
 * single column.
 *
 * The sound files are generated by `scripts/generate-sounds.js`.
 */

export type CueName =
  | 'deal'
  | 'flip'
  | 'chip'
  | 'raise'
  | 'fold'
  | 'reveal'
  | 'win'
  | 'winBig'
  | 'lose'
  | 'push'
  | 'bust'
  | 'tap';

export type HapticKind = 'selection' | 'light' | 'medium' | 'heavy' | 'success' | 'warning' | 'error';

export interface CueSpec {
  /** The bundled asset, as returned by Metro's `require`. */
  readonly source: number;
  /** 0–1. Set so no cue is startling next to the one before it. */
  readonly volume: number;
  readonly haptic: HapticKind | null;
}

export const cues: Record<CueName, CueSpec> = {
  /** A card sliding off the deck. Fires once per card, so it stays soft. */
  deal: { source: require('../../assets/sounds/deal.wav'), volume: 0.5, haptic: 'light' },

  /** A card turning over — crisper than the deal, still chrome-quiet. */
  flip: { source: require('../../assets/sounds/flip.wav'), volume: 0.4, haptic: 'selection' },

  /** A chip landing on the felt — antes and the bots' raises. */
  chip: { source: require('../../assets/sounds/chip.wav'), volume: 0.45, haptic: 'light' },

  /** The player's own raise: two chips, so committing reads bigger than anteing. */
  raise: { source: require('../../assets/sounds/raise.wav'), volume: 0.6, haptic: 'medium' },

  /** Cards pushed away — a dull knuckle knock, deliberately unresonant. */
  fold: { source: require('../../assets/sounds/fold.wav'), volume: 0.5, haptic: 'medium' },

  /** The dealer's hole cards turning — the beat the whole hand waits for. */
  reveal: { source: require('../../assets/sounds/reveal.wav'), volume: 0.6, haptic: 'medium' },

  win: { source: require('../../assets/sounds/win.m4a'), volume: 0.65, haptic: 'success' },

  /** Flush or better earns the arpeggio instead of a louder version of the same. */
  winBig: { source: require('../../assets/sounds/winBig.m4a'), volume: 0.7, haptic: 'success' },

  lose: { source: require('../../assets/sounds/lose.m4a'), volume: 0.6, haptic: 'warning' },

  /** A push or a no-qualify: one soft note — nothing happened, and it sounds like it. */
  push: { source: require('../../assets/sounds/push.m4a'), volume: 0.4, haptic: 'light' },

  /** The stack is gone. Low and slow, short of a cadence. */
  bust: { source: require('../../assets/sounds/bust.m4a'), volume: 0.7, haptic: 'error' },

  /** Menus and chrome. Deliberately the quietest cue in the set. */
  tap: { source: require('../../assets/sounds/tap.wav'), volume: 0.28, haptic: 'light' },
};
