#!/bin/bash
# Renders every icon variant from one shared mark (store/src/mark.svg) with
# headless Chrome, then installs them into assets/ and the Android res tree.
#
# The mark's own bounding box is 516x504 centred at (468,599) in a 1024 canvas;
# each variant re-centres and scales it from there. Android's adaptive icon
# treats the full image as the 108dp canvas, so the foreground is scaled to keep
# its furthest corner (325px at scale 1.0) inside the 66dp safe circle.
set -euo pipefail
cd "$(dirname "$0")/../.."
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
SRC=store/src
OUT=store/out
RES=android/app/src/main/res
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
MARK=$(cat "$SRC/mark.svg")

FELT='<defs><radialGradient id="felt" cx="50%" cy="38%" r="72%">
    <stop offset="0%" stop-color="#3DA45F"/>
    <stop offset="52%" stop-color="#2A8A4E"/>
    <stop offset="82%" stop-color="#1E6B3C"/>
    <stop offset="100%" stop-color="#14522C"/>
  </radialGradient>
  <radialGradient id="vignette" cx="50%" cy="42%" r="72%">
    <stop offset="55%" stop-color="#000000" stop-opacity="0"/>
    <stop offset="100%" stop-color="#000000" stop-opacity="0.34"/>
  </radialGradient></defs>
  <rect width="1024" height="1024" fill="url(#felt)"/>
  <rect width="1024" height="1024" fill="url(#vignette)"/>'

MONO='<defs>
  <mask id="knock">
    <rect width="1024" height="1024" fill="black"/>
    <!-- Dealer card as an outline, then the ace laid opaquely over it, then the
         spade knocked back out. One mask, so the knockout cannot expose the
         card behind it. -->
    <g transform="rotate(-23 512 792)">
      <rect x="362" y="372" width="300" height="420" rx="30" fill="none" stroke="white" stroke-width="26"/>
    </g>
    <g transform="rotate(9 512 792)">
      <rect x="362" y="372" width="300" height="420" rx="30" fill="white"/>
      <g transform="translate(512 578) scale(2.06) translate(-50 -50)">
        <path fill="black" d="M50 5 C50 5 15 39 8 56 C1 73 12 85 27 85 C37 85 45 79 48 71 C48 71 47 87 33 96 L67 96 C53 87 52 71 52 71 C55 79 63 85 73 85 C88 85 99 73 92 56 C85 39 50 5 50 5 Z"/>
      </g>
    </g>
  </mask>
</defs>
<rect width="1024" height="1024" fill="#ffffff" mask="url(#knock)"/>'

FULL="$FELT<g transform=\"translate(512 512) scale(1.34) translate(-468 -599)\">$MARK</g>"
FG="<g transform=\"translate(512 512) scale(1.0) translate(-468 -599)\">$MARK</g>"
MONO_FG="<g transform=\"translate(512 512) scale(1.0) translate(-468 -599)\">$MONO</g>"
# The legacy square icon is masked to a circle for android:roundIcon.
ROUND="<defs><clipPath id=\"circle\"><circle cx=\"512\" cy=\"512\" r=\"512\"/></clipPath></defs><g clip-path=\"url(#circle)\">$FULL</g>"

# $1 = output path, $2 = px size, $3 = inner svg body
render() {
  local path=$1 size=$2 body=$3 name
  name=$(basename "$path")
  mkdir -p "$(dirname "$path")"
  cat > "$TMP/$name.html" <<HTML
<style>html,body{margin:0;padding:0;background:transparent}svg{display:block}</style>
<svg xmlns="http://www.w3.org/2000/svg" width="$size" height="$size" viewBox="0 0 1024 1024">$body</svg>
HTML
  "$CHROME" --headless --disable-gpu --hide-scrollbars --force-device-scale-factor=1 \
    --default-background-color=00000000 --screenshot="$path" \
    --window-size="$size,$size" "file://$TMP/$name.html" 2>/dev/null
}

echo "Canonical assets:"
for v in "icon-1024 1024 FULL" "store-icon-512 512 FULL" \
         "adaptive-background-1024 1024 FELT" "adaptive-foreground-1024 1024 FG" \
         "adaptive-monochrome-1024 1024 MONO_FG" "favicon 48 FULL"; do
  set -- $v
  render "$OUT/$1.png" "$2" "${!3}"
  echo "  $OUT/$1.png"
done

echo "Installing into assets/:"
cp "$OUT/icon-1024.png"                 assets/icon.png
cp "$OUT/adaptive-foreground-1024.png"  assets/android-icon-foreground.png
cp "$OUT/adaptive-background-1024.png"  assets/android-icon-background.png
cp "$OUT/adaptive-monochrome-1024.png"  assets/android-icon-monochrome.png
cp "$OUT/favicon.png"                   assets/favicon.png
echo "  assets/{icon,android-icon-{foreground,background,monochrome},favicon}.png"

# android/ is gitignored and regenerated by prebuild, so these are written
# directly rather than via a prebuild that would also wipe the release signing
# config in app/build.gradle. app.json stays the durable source of truth.
echo "Installing into $RES:"
densities="mdpi:1 hdpi:1.5 xhdpi:2 xxhdpi:3 xxxhdpi:4"
for d in $densities; do
  dpi=${d%%:*}; factor=${d##*:}
  legacy=$(python3 -c "print(round(48*$factor))")
  adaptive=$(python3 -c "print(round(108*$factor))")
  dir="$RES/mipmap-$dpi"
  rm -f "$dir"/ic_launcher.webp "$dir"/ic_launcher_round.webp
  render "$dir/ic_launcher.png"            "$legacy"   "$FULL"
  render "$dir/ic_launcher_round.png"      "$legacy"   "$ROUND"
  render "$dir/ic_launcher_foreground.png" "$adaptive" "$FG"
  render "$dir/ic_launcher_felt.png"       "$adaptive" "$FELT"
  render "$dir/ic_launcher_monochrome.png" "$adaptive" "$MONO_FG"
  echo "  mipmap-$dpi (${legacy}px legacy, ${adaptive}px adaptive)"
done

mkdir -p "$RES/mipmap-anydpi-v26"
for n in ic_launcher ic_launcher_round; do
  cat > "$RES/mipmap-anydpi-v26/$n.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_felt"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
XML
done
echo "  mipmap-anydpi-v26/{ic_launcher,ic_launcher_round}.xml"
